// Code generated by btf2go. DO NOT EDIT.
// Shared declarations across multiple ELFs.
//
// Sources contributing to this file:
//
//	lsm.elf
//	xdp.elf
package fixture

type Pointer[T any] uint64

type BinaryIdentity struct {
	Inode uint64
	Dev   uint64
}
