// Code generated by btf2go. DO NOT EDIT.
// Shared declarations across multiple ELFs.
//
// Sources contributing to this file:
//
//	/Users/dani/btf2go/.claude/worktrees/feat-v04-aya-gaps/tests/fixtures/rust-aya/multi-elf-shared/lsm.elf  (run at 2026-05-11T05:17:25Z)
//	/Users/dani/btf2go/.claude/worktrees/feat-v04-aya-gaps/tests/fixtures/rust-aya/multi-elf-shared/xdp.elf  (run at 2026-05-11T05:17:25Z)
package fixture

type Pointer[T any] uint64

type BinaryIdentity struct {
	Inode uint64
	Dev   uint64
}
