// Code generated by btf2go. DO NOT EDIT.
// Shared declarations across multiple ELFs.
//
// Sources contributing to this file:
//
//	tests/fixtures/rust-aya/multi-elf-shared/xdp.elf  (run at 2026-05-11T04:59:28Z)
package fixture

type Pointer[T any] uint64

type BinaryIdentity struct {
	Inode uint64
	Dev   uint64
}
