// Code generated by btf2go. DO NOT EDIT.
// Source: tests/fixtures/c/events.elf
// Tool:   v0.3.1

package eventspkg

import "unsafe"

type Pointer[T any] uint64

type PayloadT struct{ _data [1]uint64 }

func (u *PayloadT) AsRaw() *uint64    { return (*uint64)(unsafe.Pointer(&u._data)) }
func (u *PayloadT) SetAsRaw(v uint64) { *(*uint64)(unsafe.Pointer(&u._data)) = v }

func (u *PayloadT) AsPair() *InnerT    { return (*InnerT)(unsafe.Pointer(&u._data)) }
func (u *PayloadT) SetAsPair(v InnerT) { *(*InnerT)(unsafe.Pointer(&u._data)) = v }

type InnerT struct {
	Lo uint32
	Hi uint32
}

type EventsT struct {
	Kind  uint8
	_pad0 [3]byte
	Pid   uint32
	_bf0  [1]byte
	_pad1 [7]byte
	Ts    uint64
	Comm  [16]int8
	Pay   PayloadT
}

func (s *EventsT) GetFlagA() uint8 {
	var v uint64
	v |= uint64(s._bf0[0]) << 0
	v = (v >> 0) & 0x1
	return uint8(v)
}

func (s *EventsT) SetFlagA(val uint8) {
	v := uint64(val) & 0x1
	{
		byteMask := byte(((uint64(0x1) << 0) >> 0) & 0xff)
		newByte := byte((v<<0)>>0) & byteMask
		s._bf0[0] = (s._bf0[0] &^ byteMask) | newByte
	}
}

func (s *EventsT) GetFlagB() uint8 {
	var v uint64
	v |= uint64(s._bf0[0]) << 0
	v = (v >> 1) & 0x1
	return uint8(v)
}

func (s *EventsT) SetFlagB(val uint8) {
	v := uint64(val) & 0x1
	{
		byteMask := byte(((uint64(0x1) << 1) >> 0) & 0xff)
		newByte := byte((v<<1)>>0) & byteMask
		s._bf0[0] = (s._bf0[0] &^ byteMask) | newByte
	}
}

func (s *EventsT) GetPrio() uint8 {
	var v uint64
	v |= uint64(s._bf0[0]) << 0
	v = (v >> 2) & 0x3f
	return uint8(v)
}

func (s *EventsT) SetPrio(val uint8) {
	v := uint64(val) & 0x3f
	{
		byteMask := byte(((uint64(0x3f) << 2) >> 0) & 0xff)
		newByte := byte((v<<2)>>0) & byteMask
		s._bf0[0] = (s._bf0[0] &^ byteMask) | newByte
	}
}
