// Code generated by btf2go. DO NOT EDIT.
// Source: tests/fixtures/rust-aya/maps-happy/maps-happy.elf
// Tool:   v0.3.2

package fixture

type Pointer[T any] uint64

type BareStruct struct {
	A uint32
	B uint32
}
