// Code generated by btf2go. DO NOT EDIT.
// Source: events.o
// Tool:   v0.5.0

package eventspkg

import "unsafe"

type Pointer[T any] uint64

type EventsPayloadT struct{ _data [1]uint64 }

func (u *EventsPayloadT) AsRaw() *uint64    { return (*uint64)(unsafe.Pointer(&u._data)) }
func (u *EventsPayloadT) SetAsRaw(v uint64) { *(*uint64)(unsafe.Pointer(&u._data)) = v }

func (u *EventsPayloadT) AsPair() *EventsInnerT    { return (*EventsInnerT)(unsafe.Pointer(&u._data)) }
func (u *EventsPayloadT) SetAsPair(v EventsInnerT) { *(*EventsInnerT)(unsafe.Pointer(&u._data)) = v }

type EventsInnerT struct {
	Lo uint32
	Hi uint32
}

type EventsEventsT struct {
	Kind         uint8
	_pad0        [3]byte
	Pid          uint32
	FlagsAndPrio uint8
	_pad1        [7]byte
	Ts           uint64
	Comm         [16]uint8
	Pay          EventsPayloadT
}
