// Code generated by btf2go. DO NOT EDIT.
// Source: maps-happy.elf
// Tool:   v0.3.2

package fixture

type Pointer[T any] uint64

type BinaryIdentity struct {
	Inode uint64
	Dev   uint64
}

type FooEvent struct {
	Kind uint32
	Seq  uint32
	Data [16]uint8
}

type ScaffoldPing struct {
	TimestampNs uint64
	Pid         uint32
	Pad         uint32
}
