// Code generated by btf2go. DO NOT EDIT.
// Source: fixture.elf
// Tool:   v0.5.0

package eventspkg

import "unsafe"

type Pointer[T any] uint64

type PayloadT struct{ _data [1]uint64 }

func (u *PayloadT) AsRaw() *uint64    { return (*uint64)(unsafe.Pointer(&u._data)) }
func (u *PayloadT) SetAsRaw(v uint64) { *(*uint64)(unsafe.Pointer(&u._data)) = v }

func (u *PayloadT) AsPair() *InnerT    { return (*InnerT)(unsafe.Pointer(&u._data)) }
func (u *PayloadT) SetAsPair(v InnerT) { *(*InnerT)(unsafe.Pointer(&u._data)) = v }

type InnerT struct {
	Lo uint32
	Hi uint32
}

type EventsT struct {
	Kind         uint8
	_pad0        [3]byte
	Pid          uint32
	FlagsAndPrio uint8
	_pad1        [7]byte
	Ts           uint64
	Comm         [16]uint8
	Pay          PayloadT
}

type FlagsT struct {
	Enabled  bool
	Readonly bool
	Debug    bool
	_pad0    [1]byte
	Seq      uint32
}
