// Package generator implements Phase 5: turn a types.GoFile into a
// formatted .go source file.
//
// Implementation note: codegen uses strings.Builder rather than
// text/template. Bitfield Get/Set accessor bodies are mostly bit math
// (shift/mask, conditional sign-extension, per-byte spill placement)
// which is awkward to express in Go's template language. The trade-off
// is that file scaffolding (header, package, imports, Pointer wrapper)
// also lives in the same Go-string code rather than in a template
// file. The templates/file.tmpl file is retained as documentation of
// the file shape only.
package generator

import (
	"fmt"
	"go/format"
	"os"
	"strings"

	"github.com/danigoland/btf2go/internal/types"
)

// Options controls codegen behavior. The Source path and ToolVersion
// are recorded in the generated file's header comment.
type Options struct {
	Source      string
	ToolVersion string
}

// Generate renders the IR to formatted Go source. On formatter failure
// the unformatted bytes are returned alongside the formatter error so
// the caller may still write them to disk for debugging.
func Generate(f *types.GoFile, opts Options) ([]byte, error) {
	rendered, err := render(f, opts)
	if err != nil {
		return nil, err
	}
	formatted, fErr := format.Source(rendered)
	if fErr != nil {
		// Print the unformatted source to stderr so the developer can
		// debug template/codegen issues. The unformatted bytes are
		// still returned so the caller may write them to disk.
		_, _ = fmt.Fprintln(os.Stderr, string(rendered))
		return rendered, fmt.Errorf("go/format: %w", fErr)
	}
	return formatted, nil
}

// sanitizeHeaderField escapes carriage returns and continues newlines
// with a "// " prefix so that opts.Source / opts.ToolVersion cannot
// break out of the file's leading comment block (preventing a class of
// generated-code injection).
var sanitizeHeaderField = strings.NewReplacer("\r", " ", "\n", "\n// ").Replace

func render(f *types.GoFile, opts Options) ([]byte, error) {
	needsUnsafe := len(f.Unions) > 0
	var sb strings.Builder
	sb.WriteString("// Code generated by btf2go. DO NOT EDIT.\n")
	fmt.Fprintf(&sb, "// Source: %s\n// Tool:   %s\n\n",
		sanitizeHeaderField(opts.Source),
		sanitizeHeaderField(opts.ToolVersion))
	fmt.Fprintf(&sb, "package %s\n\n", f.Package)
	if needsUnsafe {
		sb.WriteString("import \"unsafe\"\n\n")
		// Touch unsafe defensively; the union accessor loop below uses
		// unsafe.Pointer so the import is normally live, but this keeps
		// the file valid even if accessor lists are empty.
		sb.WriteString("var _ = unsafe.Sizeof(uintptr(0))\n\n")
	}
	sb.WriteString("type Pointer[T any] uint64\n\n")

	for _, e := range f.Enums {
		fmt.Fprintf(&sb, "type %s %s\n\nconst (\n", e.Name, e.Underlying)
		for _, v := range e.Values {
			renderEnumValue(&sb, e, v)
		}
		sb.WriteString(")\n\n")
	}
	for _, u := range f.Unions {
		fmt.Fprintf(&sb, "type %s struct { %s }\n\n", u.Name, u.Storage)
		for _, a := range u.Accessors {
			fmt.Fprintf(&sb, "func (u *%s) As%s() *%s { return (*%s)(unsafe.Pointer(&u._data)) }\n",
				u.Name, a.Name, a.GoType, a.GoType)
			fmt.Fprintf(&sb, "func (u *%s) SetAs%s(v %s) { *(*%s)(unsafe.Pointer(&u._data)) = v }\n\n",
				u.Name, a.Name, a.GoType, a.GoType)
		}
	}
	for _, s := range f.Structs {
		fmt.Fprintf(&sb, "type %s struct {\n", s.Name)
		for _, fld := range s.Fields {
			fmt.Fprintf(&sb, "\t%s %s\n", fld.Name, fld.GoType)
		}
		sb.WriteString("}\n\n")
		for _, bb := range s.Bitfields {
			for _, a := range bb.Accessors {
				renderBitAccessor(&sb, s.Name, bb, a)
			}
		}
	}
	return []byte(sb.String()), nil
}

// renderEnumValue formats a single enum const. When the enum is signed,
// the uint64-stored value is reinterpreted as signed (sign-extending
// from the underlying width) so negative constants render as "-1"
// rather than as a huge positive number.
func renderEnumValue(sb *strings.Builder, e types.GoEnum, v types.GoEnumValue) {
	if !e.Signed {
		fmt.Fprintf(sb, "\t%s %s = %d\n", v.Name, e.Name, v.Value)
		return
	}
	var signed int64
	switch e.Underlying {
	case "int8":
		signed = int64(int8(v.Value))
	case "int16":
		signed = int64(int16(v.Value))
	case "int32":
		signed = int64(int32(v.Value))
	default: // int64
		signed = int64(v.Value)
	}
	fmt.Fprintf(sb, "\t%s %s = %d\n", v.Name, e.Name, signed)
}

// renderBitAccessor emits Get/Set methods for a single bitfield.
//
// Layout: bit i of the storage block lives in byte i/8 at bit (i%8).
// Get<Name> reads `span` bytes starting at startByte, ORs them shifted
// into a uint64, shifts down by bitInByte, masks to BitWidth, and (if
// Signed) sign-extends. Set<Name> masks the input value to BitWidth
// bits, then for each affected byte writes (byte((v<<bitInByte)>>i*8))
// after clearing that byte's portion of the field's mask.
//
// Widths up to 64 bits are supported; widths >64 emit a comment-only
// stub (v0.1 limitation).
func renderBitAccessor(sb *strings.Builder, structName string, bb types.GoBitfieldBlock, a types.GoBitAccessor) {
	if a.BitWidth > 64 {
		fmt.Fprintf(sb, "// Get%s/Set%s: bitfield wider than 64 bits is not supported by btf2go v0.1\n\n", a.Name, a.Name)
		return
	}
	// Go semantics: uint64(1)<<64 == 0, so mask = 0-1 = ^uint64(0) when
	// BitWidth is exactly 64. That is the correct full mask.
	mask := (uint64(1) << a.BitWidth) - 1
	startByte := a.BitOffset / 8
	bitInByte := a.BitOffset % 8
	span := (bitInByte + a.BitWidth + 7) / 8
	if span > 8 {
		span = 8
	}

	// --- Getter ---
	fmt.Fprintf(sb, "func (s *%s) Get%s() %s {\n", structName, a.Name, a.GoType)
	sb.WriteString("\tvar v uint64\n")
	for i := uint32(0); i < span; i++ {
		fmt.Fprintf(sb, "\tv |= uint64(s.%s[%d]) << %d\n", bb.StorageField, startByte+i, i*8)
	}
	fmt.Fprintf(sb, "\tv = (v >> %d) & 0x%x\n", bitInByte, mask)
	if a.Signed && a.BitWidth > 0 && a.BitWidth < 64 {
		// Sign-extend: if the top bit of the field is set, OR in all
		// bits above the field. We use the bitwise complement of the
		// field mask rather than `^uint64(0) << BitWidth`, because the
		// latter is a constant expression that overflows uint64 when
		// the Go compiler folds it for small widths.
		fmt.Fprintf(sb, "\tif v&(1<<%d) != 0 {\n\t\tv |= ^uint64(0x%x)\n\t}\n", a.BitWidth-1, mask)
	}
	fmt.Fprintf(sb, "\treturn %s(v)\n}\n\n", a.GoType)

	// --- Setter ---
	// Unified placement formula: for byte i in [0, span), the bits we
	// want in storage byte (startByte+i) are byte((v<<bitInByte)>>i*8)
	// masked to that byte's portion of the field mask. This covers
	// both the "field starts mid-byte" case (i=0, shift left by
	// bitInByte) and the "spill into higher bytes" case (i>0, shift
	// right after the same left-shift) without an if/else branch.
	fmt.Fprintf(sb, "func (s *%s) Set%s(val %s) {\n", structName, a.Name, a.GoType)
	fmt.Fprintf(sb, "\tv := uint64(val) & 0x%x\n", mask)
	for i := uint32(0); i < span; i++ {
		fmt.Fprintf(sb, "\t{\n")
		// Parenthesize fully so left-to-right same-precedence shifts
		// don't accidentally mask before shifting.
		fmt.Fprintf(sb, "\t\tbyteMask := byte(((uint64(0x%x) << %d) >> %d) & 0xff)\n", mask, bitInByte, i*8)
		fmt.Fprintf(sb, "\t\tnewByte := byte((v << %d) >> %d) & byteMask\n", bitInByte, i*8)
		fmt.Fprintf(sb, "\t\ts.%s[%d] = (s.%s[%d] &^ byteMask) | newByte\n", bb.StorageField, startByte+i, bb.StorageField, startByte+i)
		fmt.Fprintf(sb, "\t}\n")
	}
	sb.WriteString("}\n\n")
}
