package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestScanSharedFile_Empty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	got, err := ScanSharedFile(path)
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	if len(got) != 0 {
		t.Errorf("got %v, want empty", got)
	}
}

func TestScanSharedFile_TypeNames(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	body := `// Code generated by btf2go. DO NOT EDIT.
package bpfgen

type Pointer[T any] uint64

type BinaryIdentity struct {
    Inode uint64
    Dev   uint64
}

type SomeAlias = uint32
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := ScanSharedFile(path)
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	for _, n := range []string{"Pointer", "BinaryIdentity", "SomeAlias"} {
		if !got[n] {
			t.Errorf("missing %q in %v", n, got)
		}
	}
}

func TestMergeSharedFile_FirstWrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	err := MergeSharedFile(MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/path/to/elf",
		PointerDecl: pointerDecl(),
	})
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	data, _ := os.ReadFile(path)
	s := string(data)
	if !strings.Contains(s, "package bpfgen") {
		t.Errorf("missing package: %s", s)
	}
	if !strings.Contains(s, "type Pointer[T any] uint64") {
		t.Errorf("missing Pointer: %s", s)
	}
	if !strings.Contains(s, "/path/to/elf") {
		t.Errorf("missing source path: %s", s)
	}
}

func TestMergeSharedFile_IdempotentReRun(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	args := MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/lsm.elf",
		PointerDecl: pointerDecl(),
		SharedTypeDefs: map[string]string{
			"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n\tDev   uint64\n}\n",
		},
	}
	if err := MergeSharedFile(args); err != nil {
		t.Fatalf("first: %v", err)
	}
	args.SourcePath = "/xdp.elf"
	if err := MergeSharedFile(args); err != nil {
		t.Fatalf("second: %v", err)
	}
	data, _ := os.ReadFile(path)
	s := string(data)
	if !strings.Contains(s, "/lsm.elf") || !strings.Contains(s, "/xdp.elf") {
		t.Errorf("missing source paths: %s", s)
	}
	if c := strings.Count(s, "type BinaryIdentity struct"); c != 1 {
		t.Errorf("BinaryIdentity declared %d times, want 1", c)
	}
}

func TestMergeSharedFile_ShapeMismatch(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	a := MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/lsm.elf",
		PointerDecl: pointerDecl(),
		SharedTypeDefs: map[string]string{
			"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n}\n",
		},
	}
	if err := MergeSharedFile(a); err != nil {
		t.Fatalf("first: %v", err)
	}
	b := a
	b.SourcePath = "/xdp.elf"
	b.SharedTypeDefs = map[string]string{
		"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n\tDev   uint64\n}\n",
	}
	err := MergeSharedFile(b)
	if err == nil || !strings.Contains(err.Error(), "shape mismatch") {
		t.Fatalf("err = %v, want shape mismatch", err)
	}
}

func pointerDecl() string { return "type Pointer[T any] uint64\n" }
