package generator

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestScanSharedFile_Empty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	got, err := ScanSharedFile(path)
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	if len(got) != 0 {
		t.Errorf("got %v, want empty", got)
	}
}

func TestScanSharedFile_TypeNames(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	body := `// Code generated by btf2go. DO NOT EDIT.
package bpfgen

type Pointer[T any] uint64

type BinaryIdentity struct {
    Inode uint64
    Dev   uint64
}

type SomeAlias = uint32
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := ScanSharedFile(path)
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	for _, n := range []string{"Pointer", "BinaryIdentity", "SomeAlias"} {
		if !got[n] {
			t.Errorf("missing %q in %v", n, got)
		}
	}
}

func TestMergeSharedFile_FirstWrite(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	err := MergeSharedFile(MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/path/to/elf",
		PointerDecl: pointerDecl(),
	})
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, "package bpfgen") {
		t.Errorf("missing package: %s", s)
	}
	if !strings.Contains(s, "type Pointer[T any] uint64") {
		t.Errorf("missing Pointer: %s", s)
	}
	if !strings.Contains(s, "/path/to/elf") {
		t.Errorf("missing source path: %s", s)
	}
}

func TestMergeSharedFile_IdempotentReRun(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	args := MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/lsm.elf",
		PointerDecl: pointerDecl(),
		SharedTypeDefs: map[string]string{
			"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n\tDev   uint64\n}\n",
		},
	}
	if err := MergeSharedFile(args); err != nil {
		t.Fatalf("first: %v", err)
	}
	args.SourcePath = "/xdp.elf"
	if err := MergeSharedFile(args); err != nil {
		t.Fatalf("second: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	s := string(data)
	if !strings.Contains(s, "/lsm.elf") || !strings.Contains(s, "/xdp.elf") {
		t.Errorf("missing source paths: %s", s)
	}
	if c := strings.Count(s, "type BinaryIdentity struct"); c != 1 {
		t.Errorf("BinaryIdentity declared %d times, want 1", c)
	}
}

func TestMergeSharedFile_ShapeMismatch(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	a := MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/lsm.elf",
		PointerDecl: pointerDecl(),
		SharedTypeDefs: map[string]string{
			"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n}\n",
		},
	}
	if err := MergeSharedFile(a); err != nil {
		t.Fatalf("first: %v", err)
	}
	b := a
	b.SourcePath = "/xdp.elf"
	b.SharedTypeDefs = map[string]string{
		"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n\tDev   uint64\n}\n",
	}
	err := MergeSharedFile(b)
	if err == nil || !strings.Contains(err.Error(), "shape mismatch") {
		t.Fatalf("err = %v, want shape mismatch", err)
	}
}

func pointerDecl() string { return "type Pointer[T any] uint64\n" }

func TestMergeSharedFile_BitIdenticalAcrossRuns(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	args := MergeArgs{
		Path:        path,
		Package:     "bpfgen",
		SourcePath:  "/lsm.elf",
		PointerDecl: pointerDecl(),
		SharedTypeDefs: map[string]string{
			"BinaryIdentity": "type BinaryIdentity struct {\n\tInode uint64\n\tDev   uint64\n}\n",
		},
	}
	if err := MergeSharedFile(args); err != nil {
		t.Fatalf("first: %v", err)
	}
	first, _ := os.ReadFile(path)

	// Identical re-run (same args) should produce byte-identical output.
	if err := MergeSharedFile(args); err != nil {
		t.Fatalf("second: %v", err)
	}
	second, _ := os.ReadFile(path)

	if !bytes.Equal(first, second) {
		t.Errorf("non-deterministic shared file across runs\n--- first ---\n%s\n--- second ---\n%s", first, second)
	}
}

func TestScanSharedFile_CapturesMethodAccessors(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	body := `// Code generated by btf2go. DO NOT EDIT.
// Shared declarations across multiple ELFs.
//
// Sources contributing to this file:
//   /lsm.elf
package bpfgen

type Pointer[T any] uint64

type Packed struct {
	_bf0 [4]byte
}

func (s *Packed) GetA() uint32 {
	var v uint64
	v |= uint64(s._bf0[0]) << 0
	v = (v >> 0) & 0xff
	return uint32(v)
}

func (s *Packed) SetA(val uint32) {
	v := uint64(val) & 0xff
	{
		byteMask := byte(((uint64(0xff) << 0) >> 0) & 0xff)
		newByte := byte((v << 0) >> 0) & byteMask
		s._bf0[0] = (s._bf0[0] &^ byteMask) | newByte
	}
}

type Plain struct {
	X uint32
}
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	bodies, _, err := parseSharedFile(path)
	if err != nil {
		t.Fatalf("err = %v", err)
	}

	packed := bodies["Packed"]
	if !strings.Contains(packed, "func (s *Packed) GetA()") {
		t.Errorf("Packed body missing GetA method:\n%s", packed)
	}
	if !strings.Contains(packed, "func (s *Packed) SetA(") {
		t.Errorf("Packed body missing SetA method:\n%s", packed)
	}
	plain := bodies["Plain"]
	if strings.Contains(plain, "func") {
		t.Errorf("Plain body unexpectedly contains a func:\n%s", plain)
	}
}

func TestParseSharedFile_LegacyTimestampFormat(t *testing.T) {
	// Verify that files produced by btf2go v0.4.x (with timestamps) are
	// still parsed correctly after the Gap 8 fix.
	dir := t.TempDir()
	path := filepath.Join(dir, "shared.go")
	body := `// Code generated by btf2go. DO NOT EDIT.
// Shared declarations across multiple ELFs.
//
// Sources contributing to this file:
//
//	lsm.elf  (run at 2026-05-11T06:18:23Z)
//	xdp.elf  (run at 2026-05-11T06:18:23Z)
package fixture

type Pointer[T any] uint64

type BinaryIdentity struct {
	Inode uint64
	Dev   uint64
}
`
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	_, sources, err := parseSharedFile(path)
	if err != nil {
		t.Fatalf("err = %v", err)
	}
	if len(sources) != 2 {
		t.Fatalf("want 2 sources, got %d: %v", len(sources), sources)
	}
	if sources[0] != "lsm.elf" || sources[1] != "xdp.elf" {
		t.Errorf("unexpected sources: %v", sources)
	}
}
